places=['estados unidos', 'rumania','nameku', 'marte', 'ver a los dinosaurios']
print(places)
sorted(places)
print(sorted(places))
print(sorted(places, reverse=True))
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)